class NavItem {
  final String id;
  final String label;
  final String icon;
  final String table;
  final List<String> columns;

  const NavItem({
    required this.id,
    required this.label,
    required this.icon,
    required this.table,
    required this.columns,
  });
}

class NavConfig {
  static const Map<String, List<NavItem>> config = {
    'admin': [
      NavItem(id: 'dashboard', label: 'Tableau de bord', icon: 'dashboard', table: '', columns: []),
      NavItem(id: 'parcelles', label: 'Parcelles', icon: 'grass', table: 'parcelles', columns: ['code','nom','superficie_ha','variete_canne','maturite_pct','statut','secteur']),
      NavItem(id: 'production', label: 'Production', icon: 'factory', table: 'production_journaliere', columns: ['date_prod','canne_broyee_t','sucre_blanc_t','sucre_roux_t','rendement_pct']),
      NavItem(id: 'qualite', label: 'Contrôle Qualité', icon: 'verified', table: 'controles_qualite', columns: ['date_controle','lot_reference','produit','humidite_pct','polarite','conforme']),
      NavItem(id: 'ventes', label: 'Commandes & Ventes', icon: 'shopping_cart', table: 'commandes_ventes', columns: ['numero_cmd','client_nom','client_type','produit','quantite_t','prix_unitaire_usd','montant_total_usd','statut']),
      NavItem(id: 'livraisons', label: 'Livraisons', icon: 'local_shipping', table: 'livraisons', columns: ['numero_livraison','date_livraison','transporteur','destination','quantite_t','statut']),
      NavItem(id: 'employes', label: 'Employés', icon: 'people', table: 'employes', columns: ['matricule','nom_complet','poste','departement','date_embauche','type_contrat','salaire_base_usd','statut']),
      NavItem(id: 'presences', label: 'Présences', icon: 'schedule', table: 'presences', columns: ['date_presence','heure_arrivee','heure_depart','statut','heures_travaillees']),
      NavItem(id: 'paies', label: 'Paies', icon: 'payments', table: 'paies', columns: ['mois','annee','salaire_base_usd','primes_usd','deductions_usd','salaire_net_usd','statut']),
      NavItem(id: 'conges', label: 'Congés', icon: 'beach_access', table: 'conges', columns: ['type_conge','date_debut','date_fin','nb_jours','statut']),
      NavItem(id: 'formations', label: 'Formations', icon: 'school', table: 'formations', columns: ['titre','formateur','date_debut','date_fin','lieu','budget_usd','statut']),
      NavItem(id: 'equipements', label: 'Équipements', icon: 'precision_manufacturing', table: 'equipements', columns: ['code','nom','type_equipement','marque','modele','etat','localisation']),
      NavItem(id: 'maintenance', label: 'Maintenance', icon: 'build', table: 'interventions_maintenance', columns: ['date_intervention','type_intervention','description','duree_heures','cout_usd','statut']),
      NavItem(id: 'finances', label: 'Finances', icon: 'account_balance', table: 'transactions_financieres', columns: ['date_transaction','type_transaction','categorie','description','montant_usd','statut']),
      NavItem(id: 'stocks', label: 'Stocks', icon: 'inventory', table: 'stocks_produits', columns: ['produit','quantite_t','emplacement','lot_reference','date_production','statut_qualite']),
      NavItem(id: 'intrants', label: 'Intrants Agricoles', icon: 'science', table: 'intrants_agricoles', columns: ['nom','type_intrant','quantite_stock','unite','seuil_alerte','prix_unitaire_usd','fournisseur']),
      NavItem(id: 'meteo', label: 'Météo', icon: 'cloud', table: 'donnees_meteo', columns: ['date_observation','temperature_c','humidite_pct','precipitation_mm','vent_kmh','conditions']),
      NavItem(id: 'campagnes', label: 'Campagnes', icon: 'agriculture', table: 'campagnes_agricoles', columns: ['nom','saison','date_debut','date_fin','superficie_totale_ha','rendement_prevu_t_ha','statut']),
      NavItem(id: 'rapports', label: 'Rapports Terrain', icon: 'assignment', table: 'rapports_terrain', columns: ['date_rapport','type_rapport','description','niveau_alerte','recommandations']),
      NavItem(id: 'analyses', label: 'Analyses Sol', icon: 'biotech', table: 'analyses_sol', columns: ['date_prelevement','ph','azote_mg_kg','phosphore_mg_kg','potassium_mg_kg','etat_global']),
      NavItem(id: 'journal_campagne', label: 'Journal Campagne', icon: 'edit_note', table: 'journal_campagne', columns: ['date_entry','activite','parcelles_concernees','quantite','unite','observations']),
      NavItem(id: 'documents', label: 'Documents', icon: 'folder', table: 'documents', columns: ['titre','type_document','categorie','format','taille_ko']),
    ],
    'directeur': [
      NavItem(id: 'dashboard', label: 'Tableau de bord', icon: 'dashboard', table: '', columns: []),
      NavItem(id: 'parcelles', label: 'Parcelles', icon: 'grass', table: 'parcelles', columns: ['code','nom','superficie_ha','variete_canne','maturite_pct','statut','secteur']),
      NavItem(id: 'production', label: 'Production', icon: 'factory', table: 'production_journaliere', columns: ['date_prod','canne_broyee_t','sucre_blanc_t','sucre_roux_t','rendement_pct']),
      NavItem(id: 'qualite', label: 'Contrôle Qualité', icon: 'verified', table: 'controles_qualite', columns: ['date_controle','lot_reference','produit','humidite_pct','polarite','conforme']),
      NavItem(id: 'ventes', label: 'Commandes & Ventes', icon: 'shopping_cart', table: 'commandes_ventes', columns: ['numero_cmd','client_nom','client_type','produit','quantite_t','prix_unitaire_usd','montant_total_usd','statut']),
      NavItem(id: 'livraisons', label: 'Livraisons', icon: 'local_shipping', table: 'livraisons', columns: ['numero_livraison','date_livraison','transporteur','destination','quantite_t','statut']),
      NavItem(id: 'employes', label: 'Employés', icon: 'people', table: 'employes', columns: ['matricule','nom_complet','poste','departement','date_embauche','type_contrat','salaire_base_usd','statut']),
      NavItem(id: 'paies', label: 'Paies', icon: 'payments', table: 'paies', columns: ['mois','annee','salaire_base_usd','primes_usd','deductions_usd','salaire_net_usd','statut']),
      NavItem(id: 'finances', label: 'Finances', icon: 'account_balance', table: 'transactions_financieres', columns: ['date_transaction','type_transaction','categorie','description','montant_usd','statut']),
      NavItem(id: 'stocks', label: 'Stocks', icon: 'inventory', table: 'stocks_produits', columns: ['produit','quantite_t','emplacement','lot_reference','date_production','statut_qualite']),
      NavItem(id: 'equipements', label: 'Équipements', icon: 'precision_manufacturing', table: 'equipements', columns: ['code','nom','type_equipement','marque','modele','etat','localisation']),
      NavItem(id: 'campagnes', label: 'Campagnes', icon: 'agriculture', table: 'campagnes_agricoles', columns: ['nom','saison','date_debut','date_fin','superficie_totale_ha','rendement_prevu_t_ha','statut']),
      NavItem(id: 'documents', label: 'Documents', icon: 'folder', table: 'documents', columns: ['titre','type_document','categorie','format','taille_ko']),
    ],
    'chef_agricole': [
      NavItem(id: 'dashboard', label: 'Tableau de bord', icon: 'dashboard', table: '', columns: []),
      NavItem(id: 'parcelles', label: 'Parcelles', icon: 'grass', table: 'parcelles', columns: ['code','nom','superficie_ha','variete_canne','maturite_pct','statut','secteur']),
      NavItem(id: 'rapports', label: 'Rapports Terrain', icon: 'assignment', table: 'rapports_terrain', columns: ['date_rapport','type_rapport','description','niveau_alerte','recommandations']),
      NavItem(id: 'analyses', label: 'Analyses Sol', icon: 'biotech', table: 'analyses_sol', columns: ['date_prelevement','ph','azote_mg_kg','phosphore_mg_kg','potassium_mg_kg','etat_global']),
      NavItem(id: 'intrants', label: 'Intrants Agricoles', icon: 'science', table: 'intrants_agricoles', columns: ['nom','type_intrant','quantite_stock','unite','seuil_alerte','prix_unitaire_usd','fournisseur']),
      NavItem(id: 'meteo', label: 'Météo', icon: 'cloud', table: 'donnees_meteo', columns: ['date_observation','temperature_c','humidite_pct','precipitation_mm','vent_kmh','conditions']),
      NavItem(id: 'campagnes', label: 'Campagnes', icon: 'agriculture', table: 'campagnes_agricoles', columns: ['nom','saison','date_debut','date_fin','superficie_totale_ha','rendement_prevu_t_ha','statut']),
      NavItem(id: 'journal_campagne', label: 'Journal Campagne', icon: 'edit_note', table: 'journal_campagne', columns: ['date_entry','activite','parcelles_concernees','quantite','unite','observations']),
    ],
    'chef_production': [
      NavItem(id: 'dashboard', label: 'Tableau de bord', icon: 'dashboard', table: '', columns: []),
      NavItem(id: 'production', label: 'Production', icon: 'factory', table: 'production_journaliere', columns: ['date_prod','canne_broyee_t','sucre_blanc_t','sucre_roux_t','rendement_pct']),
      NavItem(id: 'qualite', label: 'Contrôle Qualité', icon: 'verified', table: 'controles_qualite', columns: ['date_controle','lot_reference','produit','humidite_pct','polarite','conforme']),
      NavItem(id: 'stocks', label: 'Stocks', icon: 'inventory', table: 'stocks_produits', columns: ['produit','quantite_t','emplacement','lot_reference','date_production','statut_qualite']),
      NavItem(id: 'equipements', label: 'Équipements', icon: 'precision_manufacturing', table: 'equipements', columns: ['code','nom','type_equipement','marque','modele','etat','localisation']),
    ],
    'agent_terrain': [
      NavItem(id: 'dashboard', label: 'Tableau de bord', icon: 'dashboard', table: '', columns: []),
      NavItem(id: 'rapports', label: 'Rapports Terrain', icon: 'assignment', table: 'rapports_terrain', columns: ['date_rapport','type_rapport','description','niveau_alerte','recommandations']),
      NavItem(id: 'parcelles', label: 'Parcelles', icon: 'grass', table: 'parcelles', columns: ['code','nom','superficie_ha','variete_canne','maturite_pct','statut','secteur']),
      NavItem(id: 'meteo', label: 'Météo', icon: 'cloud', table: 'donnees_meteo', columns: ['date_observation','temperature_c','humidite_pct','precipitation_mm','vent_kmh','conditions']),
      NavItem(id: 'journal_campagne', label: 'Journal Campagne', icon: 'edit_note', table: 'journal_campagne', columns: ['date_entry','activite','parcelles_concernees','quantite','unite','observations']),
    ],
    'agent_rh': [
      NavItem(id: 'dashboard', label: 'Tableau de bord', icon: 'dashboard', table: '', columns: []),
      NavItem(id: 'employes', label: 'Employés', icon: 'people', table: 'employes', columns: ['matricule','nom_complet','poste','departement','date_embauche','type_contrat','salaire_base_usd','statut']),
      NavItem(id: 'presences', label: 'Présences', icon: 'schedule', table: 'presences', columns: ['date_presence','heure_arrivee','heure_depart','statut','heures_travaillees']),
      NavItem(id: 'paies', label: 'Paies', icon: 'payments', table: 'paies', columns: ['mois','annee','salaire_base_usd','primes_usd','deductions_usd','salaire_net_usd','statut']),
      NavItem(id: 'conges', label: 'Congés', icon: 'beach_access', table: 'conges', columns: ['type_conge','date_debut','date_fin','nb_jours','statut']),
      NavItem(id: 'formations', label: 'Formations', icon: 'school', table: 'formations', columns: ['titre','formateur','date_debut','date_fin','lieu','budget_usd','statut']),
    ],
    'agent_qualite': [
      NavItem(id: 'dashboard', label: 'Tableau de bord', icon: 'dashboard', table: '', columns: []),
      NavItem(id: 'qualite', label: 'Contrôle Qualité', icon: 'verified', table: 'controles_qualite', columns: ['date_controle','lot_reference','produit','humidite_pct','polarite','conforme']),
      NavItem(id: 'production', label: 'Production', icon: 'factory', table: 'production_journaliere', columns: ['date_prod','canne_broyee_t','sucre_blanc_t','sucre_roux_t','rendement_pct']),
    ],
    'agent_maintenance': [
      NavItem(id: 'dashboard', label: 'Tableau de bord', icon: 'dashboard', table: '', columns: []),
      NavItem(id: 'equipements', label: 'Équipements', icon: 'precision_manufacturing', table: 'equipements', columns: ['code','nom','type_equipement','marque','modele','etat','localisation']),
      NavItem(id: 'maintenance', label: 'Maintenance', icon: 'build', table: 'interventions_maintenance', columns: ['date_intervention','type_intervention','description','duree_heures','cout_usd','statut']),
    ],
    'agent_distribution': [
      NavItem(id: 'dashboard', label: 'Tableau de bord', icon: 'dashboard', table: '', columns: []),
      NavItem(id: 'ventes', label: 'Commandes & Ventes', icon: 'shopping_cart', table: 'commandes_ventes', columns: ['numero_cmd','client_nom','client_type','produit','quantite_t','prix_unitaire_usd','montant_total_usd','statut']),
      NavItem(id: 'livraisons', label: 'Livraisons', icon: 'local_shipping', table: 'livraisons', columns: ['numero_livraison','date_livraison','transporteur','destination','quantite_t','statut']),
    ],
    'lecteur': [
      NavItem(id: 'dashboard', label: 'Tableau de bord', icon: 'dashboard', table: '', columns: []),
      NavItem(id: 'parcelles', label: 'Parcelles', icon: 'grass', table: 'parcelles', columns: ['code','nom','superficie_ha','variete_canne','maturite_pct','statut','secteur']),
      NavItem(id: 'production', label: 'Production', icon: 'factory', table: 'production_journaliere', columns: ['date_prod','canne_broyee_t','sucre_blanc_t','sucre_roux_t','rendement_pct']),
    ],
  };

  static List<NavItem> getNavForRole(String role) {
    return config[role] ?? config['lecteur']!;
  }

  static const Map<String, String> columnLabels = {
    'code': 'Code',
    'nom': 'Nom',
    'superficie_ha': 'Superficie (ha)',
    'variete_canne': 'Variété',
    'maturite_pct': 'Maturité (%)',
    'statut': 'Statut',
    'secteur': 'Secteur',
    'date_prod': 'Date',
    'canne_broyee_t': 'Canne (t)',
    'sucre_blanc_t': 'Sucre blanc (t)',
    'sucre_roux_t': 'Sucre roux (t)',
    'rendement_pct': 'Rendement (%)',
    'date_controle': 'Date contrôle',
    'lot_reference': 'Lot',
    'produit': 'Produit',
    'humidite_pct': 'Humidité (%)',
    'polarite': 'Polarité',
    'conforme': 'Conforme',
    'numero_cmd': 'N° commande',
    'client_nom': 'Client',
    'client_type': 'Type client',
    'quantite_t': 'Quantité (t)',
    'prix_unitaire_usd': 'Prix unitaire (USD)',
    'montant_total_usd': 'Montant total (USD)',
    'numero_livraison': 'N° livraison',
    'date_livraison': 'Date',
    'transporteur': 'Transporteur',
    'destination': 'Destination',
    'matricule': 'Matricule',
    'nom_complet': 'Nom complet',
    'poste': 'Poste',
    'departement': 'Département',
    'date_embauche': 'Date embauche',
    'type_contrat': 'Type contrat',
    'salaire_base_usd': 'Salaire base (USD)',
    'date_presence': 'Date',
    'heure_arrivee': 'Heure arrivée',
    'heure_depart': 'Heure départ',
    'heures_travaillees': 'Heures travaillées',
    'mois': 'Mois',
    'annee': 'Année',
    'primes_usd': 'Primes (USD)',
    'deductions_usd': 'Déductions (USD)',
    'salaire_net_usd': 'Salaire net (USD)',
    'type_conge': 'Type congé',
    'date_debut': 'Date début',
    'date_fin': 'Date fin',
    'nb_jours': 'Nb jours',
    'titre': 'Titre',
    'formateur': 'Formateur',
    'lieu': 'Lieu',
    'budget_usd': 'Budget (USD)',
    'type_equipement': 'Type',
    'marque': 'Marque',
    'modele': 'Modèle',
    'etat': 'État',
    'localisation': 'Localisation',
    'date_intervention': 'Date',
    'type_intervention': 'Type',
    'description': 'Description',
    'duree_heures': 'Durée (h)',
    'cout_usd': 'Coût (USD)',
    'date_transaction': 'Date',
    'type_transaction': 'Type',
    'categorie': 'Catégorie',
    'montant_usd': 'Montant (USD)',
    'emplacement': 'Emplacement',
    'date_production': 'Date production',
    'statut_qualite': 'Statut qualité',
    'type_intrant': 'Type',
    'quantite_stock': 'Qté stock',
    'unite': 'Unité',
    'seuil_alerte': 'Seuil alerte',
    'fournisseur': 'Fournisseur',
    'date_observation': 'Date',
    'temperature_c': 'Température (°C)',
    'precipitation_mm': 'Précipitation (mm)',
    'vent_kmh': 'Vent (km/h)',
    'conditions': 'Conditions',
    'saison': 'Saison',
    'superficie_totale_ha': 'Superficie totale (ha)',
    'rendement_prevu_t_ha': 'Rendement prévu (t/ha)',
    'date_rapport': 'Date',
    'type_rapport': 'Type',
    'niveau_alerte': 'Niveau alerte',
    'recommandations': 'Recommandations',
    'date_prelevement': 'Date prélèvement',
    'ph': 'pH',
    'azote_mg_kg': 'Azote (mg/kg)',
    'phosphore_mg_kg': 'Phosphore (mg/kg)',
    'potassium_mg_kg': 'Potassium (mg/kg)',
    'etat_global': 'État global',
    'date_entry': 'Date',
    'activite': 'Activité',
    'parcelles_concernees': 'Parcelles concernées',
    'quantite': 'Quantité',
    'observations': 'Observations',
    'type_document': 'Type document',
    'format': 'Format',
    'taille_ko': 'Taille (Ko)',
  };

  static String getLabel(String column) {
    return columnLabels[column] ?? column.replaceAll('_', ' ');
  }
}
